# Generated by Django 5.2.15 on 2026-06-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reference_code', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(choices=[('CIVIL', 'Civil Engineering'), ('MEP', 'Mechanical, Electrical & Plumbing'), ('ARCH', 'Architecture & Design'), ('SAFETY', 'Health, Safety & Environment (HSE)'), ('ADMIN', 'Finance & Administration')], max_length=10)),
                ('location', models.CharField(default='Hargeisa Office', max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active/Published'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
