# Generated by Django 5.2.15 on 2026-06-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default='no_reply@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default='your_account@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
