# Generated by Django 5.2.15 on 2026-06-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_email_jobapplication_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applied_at',
            new_name='applied_date',
        ),
    ]
