# Generated by Django 5.2.15 on 2026-06-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_applied_at_jobapplication_applied_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
