# Generated by Django 5.2.15 on 2026-06-17 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobrequisition'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('candidate', 'job')},
        ),
    ]
