# Generated by Django 5.2.15 on 2026-06-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applied_date',
            new_name='applied_at',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience_years',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.TextField(),
        ),
    ]
