# Generated by Django 5.2.15 on 2026-06-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_rename_applied_at_jobapplication_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
