# Generated by Django 5.2.15 on 2026-06-17 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('agreed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('equipment_assigned', models.BooleanField(default=False)),
                ('safety_training_completed', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='applicants.jobapplication')),
            ],
        ),
    ]
