# Generated by Django 5.2.15 on 2026-06-17 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('interview_type', models.CharField(choices=[('PHONE', 'Phone Screen'), ('TECHNICAL', 'Technical Review'), ('PANEL', 'Panel Interview'), ('SITE_VISIT', 'On-Site Practical Evaluation')], default='TECHNICAL', max_length=15)),
                ('scheduled_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('location_details', models.CharField(help_text='Room name, site location, or meet link', max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=15)),
                ('score', models.IntegerField(blank=True, help_text='Evaluation Score from 1 to 10', null=True)),
                ('feedback_notes', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applicants.jobapplication')),
            ],
        ),
    ]
