# Generated by Django 5.2.15 on 2026-06-17 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='interviewers',
            field=models.ManyToManyField(related_name='assigned_interviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
